# Generated by Django 4.0.3 on 2022-04-12 11:15

import django.core.serializers.json
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0073_journalentry_tags_custom_fields'),
        ('tenancy', '0007_contact_link'),
        ('ipam', '0057_created_datetimefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvpnVC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('vni', models.BigIntegerField(validators=[django.core.validators.MaxValueValidator(16777215), django.core.validators.MinValueValidator(1)])),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tenancy.tenant')),
            ],
            options={
                'verbose_name': 'EVPN Virtual Circuit',
                'verbose_name_plural': 'EVPN Virtual Circuits',
                'ordering': ('vni',),
            },
        ),
        migrations.CreateModel(
            name='EvpnVCVlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('evpn_vc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlans', to='netbox_evpn_vc.evpnvc')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('vlan', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ipam.vlan')),
            ],
            options={
                'verbose_name': 'VNI to VLAN connection',
                'verbose_name_plural': 'VNI to VLAN connections',
                'ordering': ['evpn_vc'],
            },
        ),
    ]

