# Generated by Django 4.0.4 on 2022-04-26 08:44

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0007_contact_link'),
        ('extras', '0073_journalentry_tags_custom_fields'),
        ('ipam', '0057_created_datetimefield'),
        ('netbox_evpn_vc', '0002_vc_constrain'),
    ]

    def insertData(apps, schema_editor):
        vctype = apps.get_model('netbox_evpn_vc', 'EvpnVCType')
        vctypeEntry = vctype(name = "Internal")
        vctypeEntry.save()

    operations = [
        migrations.AlterModelOptions(
            name='evpnvcvlan',
            options={'ordering': ['evpn_vc', 'vlan'], 'verbose_name': 'VNI to VLAN connection', 'verbose_name_plural': 'VNI to VLAN connections'},
        ),
        migrations.AlterField(
            model_name='evpnvc',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evpnvcs', to='tenancy.tenant'),
        ),
        migrations.AlterField(
            model_name='evpnvcvlan',
            name='vlan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evpnvcvlan', to='ipam.vlan'),
        ),
        migrations.CreateModel(
            name='EvpnVCType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'VC type',
                'verbose_name_plural': 'VC types',
                'ordering': [],
            },
        ),
        migrations.RunPython(insertData),
        migrations.AddField(
            model_name='evpnvc',
            name='vc_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='evpns', to='netbox_evpn_vc.evpnvctype'),
            preserve_default=False,
        ),
    ]
